# Set up CoreDNS
---
- name: Configure DNS on Ubuntu servers
  hosts: coredns 
  become: yes              
  roles:
    - coredns

- name: Configure Admin tools on Ubuntu servers
  hosts: 
    - coredns
    - plex
  become: yes         
  roles:
    - common

#Install plex services
- name: Configure Plex on Ubuntu servers
  hosts: plex 
  become: yes             
  roles:
    - plex
